apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: keycloak-appset
  namespace: argocd
  labels:
    name: keycloak-appset
spec:
  generators:
    - git:
        repoURL: https://github.com/tankibaj/gitops-scratch-paper.git
        revision: main
        directories:
          - path: 'components/keycloak/*'
  template:
    metadata:
      name: '{{path.basename}}'
      labels:
        app.kubernetes.io/managed-by: argocd-applicationset-controller
    spec:
      project: gitops
      source:
        repoURL: https://github.com/tankibaj/gitops-scratch-paper.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: keycloak
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
#        automated:
#          prune: true
#          selfHeal: true
