apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-public
  namespace: argocd
  labels:
    name: ingress-controller
spec:
  project: gitops
  source:
    repoURL: https://github.com/tankibaj/gitops-scratch-paper.git
    targetRevision: development
    path: components/ingress-nginx/aws-nlb
    helm:
      releaseName: nginx
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx-public
  syncPolicy:
    syncOptions:
      - CreateNamespace=true