apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: prometheus-agent-appset
  namespace: argocd
  labels:
    name: observability
spec:
  generators:
    - list:
        elements:
          - cluster: in-cluster
            url: https://kubernetes.default.svc
            values:
              tag: main
              remoteWriteURL: http://cortex-nginx.cortex.svc:80/api/v1/push/org1
#          - cluster: development
#            url: https://dev-cluster.local.naim.run
#            values:
#              tag: development
#              remoteWriteURL: https://cortex.local.naim.run/api/prom/push/org2
  template:
    metadata:
      name: 'prometheus-agent-{{cluster}}'
      labels:
        name: observability
    spec:
      project: gitops
      source:
        repoURL: https://github.com/tankibaj/gitops-scratch-paper.git
        targetRevision: main
        path: prometheus-agent/{{values.tag}}
        helm:
          skipCrds: true # https://github.com/prometheus-operator/prometheus-operator/issues/4439#issuecomment-1110279191
          releaseName: kube-prometheus
          values: |
            kube-prometheus-stack:
              prometheus:
                prometheusSpec:
                  externalLabels:
                    cluster: '{{cluster}}'
                 remoteWrite:
                   - name: cortex
                     url: '{{values.remoteWriteURL}}'
      destination:
        server: '{{url}}'
        namespace: prometheus-agent
      syncPolicy:
        syncOptions:
          - CreateNamespace=true