nameOverride: ""
fullnameOverride: "github-release-notifier"

replicaCount: 1

image:
  repository: thenaim/github-release-notifier
  pullPolicy: IfNotPresent
  tag: v1.0.0

config:
  checkInterval: "7200" # 2 hours by default
  repositories:
    - owner: tankibaj
      name: release-test
    - owner: kubernetes
      name: kubernetes
    - owner: argoproj
      name: argo-cd
    - owner: go-gitea
      name: gitea
    - owner: goharbor
      name: harbor
    - owner: vmware-tanzu
      name: velero
    - owner: kubernetes
      name: ingress-nginx
    - owner: grafana
      name: grafana
    - owner: grafana
      name: loki
    - owner: grafana
      name: mimir
    - owner: prometheus
      name: prometheus
    - owner: prometheus-operator
      name: prometheus-operator
    - owner: cortexproject
      name: cortex
    - owner: cert-manager
      name: cert-manager
    - owner: keycloak
      name: keycloak
    - owner: traefik
      name: traefik
    - owner: hashicorp
      name: vault
    - owner: hashicorp
      name: consul
    - owner: hashicorp
      name: terraform
    - owner: external-secrets
      name: external-secrets

serviceAccount:
  create: false
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}
securityContext: {}

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}