fullnameOverride: debug-kubernetes-secrets
nameOverride: ""

replicaCount: 1

container:
  name: alpine-whale
  image:
    repository: alpine-whale
    tag: curl
    pullPolicy: IfNotPresent

secret:
  name: whale-secret
#  data:
#    username: super-user
#    password: my_decrypted_password
