consul:
  server:
    replicas: 1 # default: 3
    storage: 1Gi # default: 10Gi
    resources: # # default helm chart has very limited resources allocated https://github.com/hashicorp/consul-k8s/blob/b4fb9d1cfbb0e6bdfcfd8ef1b8f171d8e8eea9e5/charts/consul/values.yaml#L777
       requests:
         memory: 100Mi
         cpu: 100m
       limits:
         memory: 128Mi
         cpu: 150m
    
  # -- Consul UI [Optional for debug]
  ui:
    enabled: true
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx-public
      ingressClassName: nginx-public
      pathType: Prefix # ImplementationSpecific
      hosts:
        - host: consul.local.naim.run
          paths:
            - / # /*