apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: prometheus-crds
  namespace: argocd
  labels:
    name: observability
spec:
  generators:
    - list:
        elements:
          - cluster: management
            url: https://kubernetes.default.svc
          - cluster: development
            url: https://172.16.100.69:16443
  template:
    metadata:
      name: 'prometheus-crds-{{cluster}}'
      labels:
        name: observability
    spec:
      project: gitops
      sources:
        - repoURL: https://github.com/tankibaj/gitops-scratch-paper.git
          targetRevision: development
          path: components/prometheus/crds/kustomization
      destination:
        server: '{{url}}'
        namespace: prometheus
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
          - Replace=true # https://github.com/prometheus-operator/prometheus-operator/issues/4439#issuecomment-1110279191