apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # -- Common resources
  - rbac/rbac-workflow-generic.yaml
  - eventbus/eventbus-default.yaml

# -- Workflow: Buildkit
#  - workflow-template/buildkit.yaml
#  - eventsource/eventsource-webhook.yaml
#  - sensor/sensor-buildkit.yaml

# -- Workflow: AWS SQS
#  - workflow-template/catalog-distribution.yaml
#  - eventsource/eventsource-aws-sqs.yaml
#  - sensor/sensor-aws-sqs.yaml

  # -- Workflow: Terraform
  - workflow-template/terraform.yaml
  - eventsource/eventsource-webhook.yaml
  - sensor/sensor-terraform.yaml

  # -- Workflow: Git Event
  - sensor/sensor-git-event.yaml

  # -- Workflow: TerraAI
  - sensor/sensor-terra-ai.yaml
  - workflow-template/terra-ai.yaml
  - workflow-template/ai-tf-apply.yaml
  - workflow-template/ai-tf-destroy.yaml

  # -- Workflow: Ansible Runner
  - workflow-template/ansible-runner.yaml