ingress-nginx:
  fullnameOverride: nginx
  controller:
    ingressClassResource:
      name: nginx-public                # -- Name of the ingressClass
      default: true                     # -- Is this the default ingressClass for the cluster
      ingressClass: nginx-public        # -- For backwards compatibility with ingress.class annotation, use ingressClass. Algorithm is as follows, first ingressClassName is considered, if not present, controller looks for ingress.class annotation.
    
    replicaCount: 1
    
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 10
      targetCPUUtilizationPercentage: 80
      targetMemoryUtilizationPercentage: 0
  
  defaultBackend:
    enabled: true
  
  extraArgs:
    default-ssl-certificate: "cert-manager/wildcard-local-naim-run-tls"