ingress-nginx:
  fullnameOverride: nginx
  controller:
    config:
      force-ssl-redirect: "true"
    ingressClassResource:
      name: nginx-public                # -- Name of the ingressClass
      default: true                     # -- Is this the default ingressClass for the cluster
      ingressClass: nginx-public        # -- For backwards compatibility with ingress.class annotation, use ingressClass. Algorithm is as follows, first ingressClassName is considered, if not present, controller looks for ingress.class annotation.
  
    resources:
      requests:
        cpu: 100m
        memory: 90Mi
    
    autoscaling:
      enabled: true
      minReplicas: 2
      maxReplicas: 10
      targetCPUUtilizationPercentage: 80
      targetMemoryUtilizationPercentage: 0
    
    extraArgs:
      default-ssl-certificate: cert-manager/wildcard-local-naim-run-tls
  
  defaultBackend:
    enabled: true