---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
  labels:
    name: demo
spec:
  generators:
    - list:
        elements:
          - cluster: development
            url: https://172.16.100.69:16443
            env: dev
          - cluster: staging
            url: https://172.16.100.70:16443
            env: qa
          - cluster: production
            url: https://kubernetes.default.svc
            env: prod
  strategy:
    type: RollingSync
    rollingSync:
      steps:
        - matchExpressions:
            - key: envLabel
              operator: In
              values:
                - dev
          #maxUpdate: 100%  # if undefined, all applications matched are updated together (default is 100%)
        - matchExpressions:
            - key: envLabel
              operator: In
              values:
                - qa
          maxUpdate: 0      # if 0, no matched applications will be updated
        - matchExpressions:
            - key: envLabel
              operator: In
              values:
                - prod
          maxUpdate: 10%    # maxUpdate supports both integer and percentage string values (rounds down, but floored at 1 Application for >0%)
  goTemplate: true
  template:
    metadata:
      name: 'guestbook-{{.cluster}}'
      labels:
        envLabel: '{{.env}}'
        name: demo
    spec:
      project: gitops
      sources:
        - repoURL: https://github.com/argoproj/argocd-example-apps.git
          path: helm-guestbook
          targetRevision: master
          helm:
            valueFiles:
              - $values/demo-progressive-rollout/values-{{.env}}.yaml
            values: |
              image:
                tag: 0.2
        - ref: values
          repoURL: https://github.com/tankibaj/gitops-scratch-paper.git
          targetRevision: development
      destination:
        server: '{{.url}}'
        namespace: guestbook
      syncPolicy:
        syncOptions:
          - CreateNamespace=true