apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: demo-helm-common-chart
  namespace: argocd
  labels:
    name: demo
spec:
  generators:
    - git:
        repoURL: https://github.com/tankibaj/gitops-scratch-paper.git
        revision: development
        directories:
          # here it will read the paths under configs and the subpaths under the config paths
          - path: demo/configs/*/*
  template:
    metadata:
      namespace: argocd
      # you can use the path strings with / delimiter as variables
      name: "{{path[2]}}-{{path.basename}}"
      labels:
        name: demo
    spec:
      project: gitops
      source:
        helm:
          # specify different values file based on directories variables
          valueFiles:
            - "configs/{{path[2]}}/{{path.basename}}/values.yaml"
            - "configs/{{path[2]}}/values.yaml"
        path: demo
        repoURL: https://github.com/tankibaj/gitops-scratch-paper.git
        targetRevision: development
#      syncPolicy:
#        automated:
#          prune: true
      destination:
        # specify different destinations
        namespace: "{{path.basename}}"
        server: https://kubernetes.default.svc
