apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - eventbus.yaml
  - eventsource/eventsource-webhook.yaml
#  - sensor/sensor-job.yaml


# -- Webhook Workflow
# -- RBAC and ServiceAccount for the sensor
  - rbac-argo-workflow/role-workflow-operator.yaml
  - rbac-argo-workflow/rolebinding-workflow-operator.yaml
  - rbac-argo-workflow/serviceaccount-workflow-operate.yaml
  - sensor/sensor-workflow.yaml